[platformio]
globallib_dir = ../../lib
src_dir = .

[env]
platform = espressif32@6.3.0
framework = arduino
upload_speed = 115200
monitor_speed = 115200
monitor_filters =
    default
    esp32_exception_decoder

[env:t-camera-sim]
extends = env
board = esp32s3box
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM
    -DCAMERA_MODEL_TTGO_T_CAM_SIM
monitor_rts = 0
monitor_dtr = 0
monitor_port = COM3
upload_port = COM3
lib_ignore =
    TFT_eSPI
    ArduinoHttpClient
board_build.partitions = default_16MB.csv